import type { Exercise } from "./types";
import { normalizeSearch } from "./format";

export const EXERCISES: Exercise[] = [
  // === SQUAT PATTERN ===
  { name: "Barbell back squat", primary: ["quads", "glutes"], secondary: ["hamstrings", "core"], equipment: "barbell", pattern: "squat" },
  { name: "Barbell front squat", primary: ["quads", "core"], secondary: ["glutes"], equipment: "barbell", pattern: "squat" },
  { name: "Goblet squat", primary: ["quads", "glutes"], secondary: ["core"], equipment: "dumbbell", pattern: "squat" },
  { name: "DB Bulgarian split squat", primary: ["quads", "glutes"], secondary: ["hamstrings", "core"], equipment: "dumbbell", pattern: "squat" },
  { name: "DB split squat to RDL", primary: ["quads", "glutes", "hamstrings"], secondary: ["core", "back"], equipment: "dumbbell", pattern: "squat" },
  { name: "DB sumo squat", primary: ["glutes", "quads"], secondary: ["hamstrings", "core"], equipment: "dumbbell", pattern: "squat" },
  { name: "Bodyweight squat", primary: ["quads", "glutes"], secondary: ["hamstrings"], equipment: "bodyweight", pattern: "squat" },
  { name: "Squat jump", primary: ["quads", "glutes"], secondary: ["calves"], equipment: "bodyweight", pattern: "plyo" },
  { name: "Skater hop", primary: ["glutes", "quads"], secondary: ["calves", "core"], equipment: "bodyweight", pattern: "plyo" },
  { name: "DB forward lunge", primary: ["quads", "glutes"], secondary: ["hamstrings", "core"], equipment: "dumbbell", pattern: "squat" },
  { name: "DB reverse lunge", primary: ["quads", "glutes"], secondary: ["hamstrings", "core"], equipment: "dumbbell", pattern: "squat" },
  { name: "DB reverse lunge w/ pulse", primary: ["quads", "glutes"], secondary: ["hamstrings", "core"], equipment: "dumbbell", pattern: "squat" },
  { name: "DB walking lunge", primary: ["quads", "glutes"], secondary: ["hamstrings", "core"], equipment: "dumbbell", pattern: "squat" },
  { name: "Barbell walking lunge", primary: ["quads", "glutes"], secondary: ["hamstrings", "core"], equipment: "barbell", pattern: "squat" },
  { name: "Lateral step-up", primary: ["quads", "glutes"], secondary: ["calves"], equipment: "dumbbell", pattern: "squat" },
  {
    name: "Box step-up",
    aliases: ["DB box step-up", "DB box step ups", "DB box step-up"],
    primary: ["quads", "glutes"],
    secondary: ["hamstrings"],
    equipment: "dumbbell",
    pattern: "squat",
  },
  { name: "DB squat to reverse lunge", primary: ["quads", "glutes"], secondary: ["hamstrings", "core"], equipment: "dumbbell", pattern: "squat" },
  { name: "Leg press", primary: ["quads", "glutes"], secondary: ["hamstrings"], equipment: "machine", pattern: "squat" },
  { name: "Angled machine leg press", primary: ["quads", "glutes"], secondary: ["hamstrings"], equipment: "machine", pattern: "squat" },
  { name: "Hack squat", primary: ["quads"], secondary: ["glutes"], equipment: "machine", pattern: "squat" },
  { name: "Leg extension", primary: ["quads"], secondary: [], equipment: "machine", pattern: "squat" },
  { name: "Wall sit", primary: ["quads"], secondary: ["core"], equipment: "bodyweight", pattern: "squat" },
  {
    name: "Wall sit with adductor squeeze",
    aliases: ["Wall sits with adductor squeeze", "Adductor squeeze wall sit", "Adductor squeeze wall sits"],
    primary: ["quads", "adductors"],
    secondary: ["core"],
    equipment: "other",
    pattern: "squat",
  },
  {
    name: "Banded wall sit abduction pulses",
    aliases: ["Banded wall sit", "Banded wall sits", "Wall sit with resistance band", "Wall sits with resistance band"],
    primary: ["quads", "glutes"],
    secondary: ["core"],
    equipment: "band",
    pattern: "squat",
  },
  { name: "Pistol squat", primary: ["quads", "glutes"], secondary: ["core", "calves"], equipment: "bodyweight", pattern: "squat" },
  { name: "Cossack squat", primary: ["quads", "glutes"], secondary: ["hamstrings"], equipment: "bodyweight", pattern: "squat" },
  { name: "Sissy squat", primary: ["quads"], secondary: [], equipment: "bodyweight", pattern: "squat" },

  // === HINGE PATTERN ===
  { name: "Barbell deadlift", primary: ["hamstrings", "glutes", "back"], secondary: ["core", "quads"], equipment: "barbell", pattern: "hinge" },
  {
    name: "Barbell Romanian deadlift",
    aliases: ["Barbell RDL", "BB RDL", "Barbell rdls"],
    primary: ["hamstrings", "glutes"],
    secondary: ["back", "core"],
    equipment: "barbell",
    pattern: "hinge",
  },
  { name: "DB Romanian deadlift", primary: ["hamstrings", "glutes"], secondary: ["back", "core"], equipment: "dumbbell", pattern: "hinge" },
  { name: "Single-leg DB RDL", primary: ["hamstrings", "glutes"], secondary: ["core"], equipment: "dumbbell", pattern: "hinge" },
  { name: "Sumo deadlift", primary: ["glutes", "hamstrings", "quads"], secondary: ["back", "core"], equipment: "barbell", pattern: "hinge" },
  { name: "Trap bar deadlift", primary: ["quads", "glutes", "hamstrings"], secondary: ["back", "core"], equipment: "barbell", pattern: "hinge" },
  { name: "Kettlebell swing", primary: ["glutes", "hamstrings"], secondary: ["core", "shoulders"], equipment: "kettlebell", pattern: "hinge" },
  { name: "Good morning", primary: ["hamstrings", "back"], secondary: ["glutes", "core"], equipment: "barbell", pattern: "hinge" },
  { name: "DB good morning", primary: ["hamstrings", "back"], secondary: ["glutes", "core"], equipment: "dumbbell", pattern: "hinge" },
  { name: "Cable pull-through", primary: ["glutes", "hamstrings"], secondary: ["core"], equipment: "cable", pattern: "hinge" },
  { name: "Cable kickback", primary: ["glutes"], secondary: ["hamstrings"], equipment: "cable", pattern: "hinge" },
  { name: "Donkey kick", primary: ["glutes"], secondary: ["hamstrings"], equipment: "bodyweight", pattern: "hinge" },
  { name: "Lateral band walk", primary: ["glutes"], secondary: ["adductors", "core"], equipment: "band", pattern: "hinge" },
  { name: "Bench single-leg hip thrust", primary: ["glutes"], secondary: ["hamstrings", "core"], equipment: "bodyweight", pattern: "hinge" },
  { name: "Barbell hip thrust", primary: ["glutes"], secondary: ["hamstrings", "core"], equipment: "barbell", pattern: "hinge" },
  { name: "Glute bridge", primary: ["glutes"], secondary: ["hamstrings"], equipment: "bodyweight", pattern: "hinge" },
  { name: "Feet-elevated glute bridge", primary: ["glutes"], secondary: ["hamstrings", "core"], equipment: "bodyweight", pattern: "hinge" },
  { name: "Banded walkout", primary: ["glutes"], secondary: ["core", "hip_flexors"], equipment: "band", pattern: "hinge" },
  { name: "Banded fire hydrant", primary: ["glutes"], secondary: ["hip_flexors"], equipment: "band", pattern: "hinge" },
  { name: "Banded clamshell", primary: ["glutes"], secondary: [], equipment: "band", pattern: "hinge" },
  { name: "Leg curl", primary: ["hamstrings"], secondary: [], equipment: "machine", pattern: "hinge" },
  { name: "Nordic hamstring curl", primary: ["hamstrings"], secondary: ["glutes"], equipment: "bodyweight", pattern: "hinge" },
  { name: "Hyperextension", primary: ["back", "glutes"], secondary: ["hamstrings"], equipment: "bodyweight", pattern: "hinge" },

  // === PUSH PATTERN ===
  { name: "DB incline bench press", primary: ["chest", "shoulders"], secondary: ["triceps"], equipment: "dumbbell", pattern: "push" },
  { name: "DB flat bench press", primary: ["chest"], secondary: ["shoulders", "triceps"], equipment: "dumbbell", pattern: "push" },
  { name: "DB floor press", primary: ["chest", "triceps"], secondary: ["shoulders"], equipment: "dumbbell", pattern: "push" },
  { name: "Barbell bench press", primary: ["chest"], secondary: ["shoulders", "triceps"], equipment: "barbell", pattern: "push" },
  {
    name: "Barbell incline bench press",
    aliases: ["Barbell incline bench"],
    primary: ["chest", "shoulders"],
    secondary: ["triceps"],
    equipment: "barbell",
    pattern: "push",
  },
  { name: "DB overhead press", primary: ["shoulders"], secondary: ["triceps", "core"], equipment: "dumbbell", pattern: "push" },
  { name: "Barbell overhead press", primary: ["shoulders"], secondary: ["triceps", "core"], equipment: "barbell", pattern: "push" },
  { name: "Barbell push press", primary: ["shoulders"], secondary: ["triceps", "core", "quads"], equipment: "barbell", pattern: "push", aliases: ["Barbell overhead push press", "Push press"] },
  { name: "DB Arnold press", primary: ["shoulders"], secondary: ["triceps"], equipment: "dumbbell", pattern: "push" },
  { name: "SA press to windmill", primary: ["shoulders", "core"], secondary: ["glutes", "triceps"], equipment: "dumbbell", pattern: "push" },
  { name: "Archer push-up", primary: ["chest"], secondary: ["shoulders", "triceps", "core"], equipment: "bodyweight", pattern: "push" },
  { name: "Incline push-up", primary: ["chest"], secondary: ["shoulders", "triceps", "core"], equipment: "bodyweight", pattern: "push" },
  { name: "Push-up", primary: ["chest"], secondary: ["shoulders", "triceps", "core"], equipment: "bodyweight", pattern: "push" },
  { name: "Hand raise push-up", primary: ["chest", "core", "shoulders"], secondary: ["triceps"], equipment: "bodyweight", pattern: "push" },
  { name: "Diamond push-up", primary: ["triceps", "chest"], secondary: ["shoulders"], equipment: "bodyweight", pattern: "push" },
  { name: "Pike push-up", primary: ["shoulders"], secondary: ["triceps"], equipment: "bodyweight", pattern: "push" },
  { name: "Dip", primary: ["chest", "triceps"], secondary: ["shoulders"], equipment: "bodyweight", pattern: "push" },
  { name: "DB lateral raise", primary: ["shoulders"], secondary: [], equipment: "dumbbell", pattern: "push" },
  { name: "DB front raise", primary: ["shoulders"], secondary: [], equipment: "dumbbell", pattern: "push" },
  { name: "DB sunrise raise", primary: ["shoulders", "rear_delts"], secondary: [], equipment: "dumbbell", pattern: "push" },
  { name: "Cable lateral raise", primary: ["shoulders"], secondary: [], equipment: "cable", pattern: "push" },
  { name: "DB prone press", primary: ["shoulders", "rear_delts"], secondary: [], equipment: "dumbbell", pattern: "push" },
  { name: "Plank to push-up", primary: ["core", "chest"], secondary: ["shoulders", "triceps"], equipment: "bodyweight", pattern: "push" },
  { name: "Push-up to renegade row", primary: ["back", "core"], secondary: ["chest", "shoulders", "triceps"], equipment: "dumbbell", pattern: "pull" },
  { name: "Tricep pushdown", primary: ["triceps"], secondary: [], equipment: "cable", pattern: "push" },
  { name: "Overhead tricep extension", primary: ["triceps"], secondary: [], equipment: "dumbbell", pattern: "push" },
  { name: "Skull crusher", primary: ["triceps"], secondary: [], equipment: "barbell", pattern: "push" },
  {
    name: "DB skull crusher",
    aliases: ["DB skullcrushers", "DB skull crushers", "DB skullcrusher"],
    primary: ["triceps"],
    secondary: [],
    equipment: "dumbbell",
    pattern: "push",
  },
  { name: "DB thruster", primary: ["quads", "shoulders"], secondary: ["glutes", "triceps", "core"], equipment: "dumbbell", pattern: "push" },
  { name: "Landmine press", primary: ["chest", "shoulders"], secondary: ["core", "triceps"], equipment: "barbell", pattern: "push" },
  { name: "Cable chest fly", primary: ["chest"], secondary: [], equipment: "cable", pattern: "push" },
  { name: "DB chest fly", primary: ["chest"], secondary: ["shoulders"], equipment: "dumbbell", pattern: "push" },

  // === PULL PATTERN ===
  { name: "Band-assisted pull-up", primary: ["back", "biceps"], secondary: ["shoulders", "core"], equipment: "band", pattern: "pull" },
  { name: "Pull-up", primary: ["back", "biceps"], secondary: ["shoulders", "core"], equipment: "bodyweight", pattern: "pull" },
  { name: "Chin-up", primary: ["biceps", "back"], secondary: ["shoulders"], equipment: "bodyweight", pattern: "pull" },
  {
    name: "Lat pulldown",
    primary: ["back"],
    secondary: ["biceps", "shoulders"],
    equipment: "cable",
    pattern: "pull",
    aliases: ["Lat pull down", "Lat pulldown machine", "Lat pull down machine"],
  },
  { name: "DB bent-over row", primary: ["back"], secondary: ["biceps", "rear_delts"], equipment: "dumbbell", pattern: "pull" },
  { name: "Barbell bent-over row", primary: ["back"], secondary: ["biceps", "rear_delts", "core"], equipment: "barbell", pattern: "pull" },
  { name: "DB single-arm row", primary: ["back"], secondary: ["biceps", "rear_delts"], equipment: "dumbbell", pattern: "pull" },
  {
    name: "Cable row",
    primary: ["back"],
    secondary: ["biceps", "rear_delts"],
    equipment: "cable",
    pattern: "pull",
    aliases: ["Cable row machine", "Seated cable row", "Seated cable row machine"],
  },
  { name: "DB renegade row", primary: ["back", "core"], secondary: ["biceps"], equipment: "dumbbell", pattern: "pull" },
  { name: "KB gorilla row", primary: ["back"], secondary: ["biceps", "core"], equipment: "kettlebell", pattern: "pull", aliases: ["Kettlebell gorilla row", "Gorilla row", "KB gorilla alternating row", "Kettlebell gorilla alternating row"] },
  { name: "Face pull", primary: ["rear_delts", "shoulders"], secondary: ["back"], equipment: "cable", pattern: "pull" },
  { name: "Band face pull", primary: ["rear_delts", "shoulders"], secondary: ["back"], equipment: "band", pattern: "pull" },
  { name: "DB hammer curl", primary: ["biceps"], secondary: [], equipment: "dumbbell", pattern: "pull" },
  { name: "Barbell curl", primary: ["biceps"], secondary: [], equipment: "barbell", pattern: "pull" },
  { name: "Concentration curl", primary: ["biceps"], secondary: [], equipment: "dumbbell", pattern: "pull" },
  { name: "Kneeling bicep curl", primary: ["biceps"], secondary: [], equipment: "dumbbell", pattern: "pull" },
  { name: "Cable curl", primary: ["biceps"], secondary: [], equipment: "cable", pattern: "pull" },
  { name: "Inverted row", primary: ["back"], secondary: ["biceps", "core"], equipment: "bodyweight", pattern: "pull" },
  { name: "T-bar row", primary: ["back"], secondary: ["biceps", "rear_delts"], equipment: "barbell", pattern: "pull" },
  { name: "Straight-arm pulldown", primary: ["back"], secondary: ["core"], equipment: "cable", pattern: "pull" },
  { name: "DB reverse fly", primary: ["rear_delts"], secondary: ["back"], equipment: "dumbbell", pattern: "pull" },
  { name: "Band pull-apart", primary: ["rear_delts"], secondary: ["back"], equipment: "band", pattern: "pull" },
  { name: "Chest-supported DB row", primary: ["back"], secondary: ["biceps", "rear_delts"], equipment: "dumbbell", pattern: "pull" },
  { name: "Preacher curl", primary: ["biceps"], secondary: [], equipment: "dumbbell", pattern: "pull" },
  { name: "Incline DB curl", primary: ["biceps"], secondary: [], equipment: "dumbbell", pattern: "pull" },
  { name: "Band external rotation", primary: ["rear_delts", "shoulders"], secondary: [], equipment: "band", pattern: "pull" },
  { name: "Prone Y raise", primary: ["back", "shoulders"], secondary: ["rear_delts"], equipment: "dumbbell", pattern: "pull" },
  { name: "Prone T raise", primary: ["rear_delts", "back"], secondary: ["shoulders"], equipment: "dumbbell", pattern: "pull" },

  // === CORE ===
  { name: "V-up", primary: ["core", "hip_flexors"], secondary: [], equipment: "bodyweight", pattern: "core" },
  { name: "Alternating V-up", primary: ["core", "hip_flexors"], secondary: [], equipment: "bodyweight", pattern: "core" },
  { name: "Single-side V-up", primary: ["core", "hip_flexors"], secondary: [], equipment: "bodyweight", pattern: "core" },
  { name: "Tuck-up", primary: ["core", "hip_flexors"], secondary: [], equipment: "bodyweight", pattern: "core" },
  { name: "Dead bug", primary: ["core"], secondary: ["hip_flexors"], equipment: "bodyweight", pattern: "core" },
  { name: "Hanging knee raise", primary: ["core", "hip_flexors"], secondary: [], equipment: "bodyweight", pattern: "core" },
  { name: "Hanging leg raise", primary: ["core", "hip_flexors"], secondary: [], equipment: "bodyweight", pattern: "core" },
  { name: "Plank", primary: ["core"], secondary: ["shoulders"], equipment: "bodyweight", pattern: "core" },
  { name: "High plank", primary: ["core", "shoulders"], secondary: ["chest"], equipment: "bodyweight", pattern: "core" },
  { name: "Plank drag", primary: ["core"], secondary: ["shoulders", "back"], equipment: "dumbbell", pattern: "core" },
  { name: "Side plank", primary: ["core"], secondary: [], equipment: "bodyweight", pattern: "core" },
  { name: "Side plank dip", primary: ["core"], secondary: [], equipment: "bodyweight", pattern: "core" },
  { name: "DB side plank rotation", primary: ["core"], secondary: ["shoulders"], equipment: "dumbbell", pattern: "core" },
  { name: "Pallof press", primary: ["core"], secondary: [], equipment: "cable", pattern: "core" },
  { name: "Cable woodchop", primary: ["core"], secondary: [], equipment: "cable", pattern: "core" },
  { name: "Oblique twist", primary: ["core"], secondary: ["hip_flexors"], equipment: "bodyweight", pattern: "core" },
  { name: "Russian twist", primary: ["core"], secondary: [], equipment: "bodyweight", pattern: "core" },
  { name: "Bicycle crunch", primary: ["core"], secondary: ["hip_flexors"], equipment: "bodyweight", pattern: "core" },
  { name: "Ab wheel rollout", primary: ["core"], secondary: ["shoulders"], equipment: "other", pattern: "core" },
  { name: "Mountain climber", primary: ["core", "hip_flexors"], secondary: ["shoulders"], equipment: "bodyweight", pattern: "core" },
  { name: "Bear crawl", primary: ["core", "shoulders"], secondary: ["glutes", "chest"], equipment: "bodyweight", pattern: "core" },
  { name: "Bear plank shoulder tap", primary: ["core", "shoulders"], secondary: ["glutes"], equipment: "bodyweight", pattern: "core" },
  { name: "High knees", primary: ["hip_flexors", "quads"], secondary: ["core", "calves"], equipment: "bodyweight", pattern: "conditioning" },
  { name: "Squat thrust", primary: ["quads", "core"], secondary: ["shoulders", "glutes"], equipment: "bodyweight", pattern: "conditioning" },
  { name: "Flutter kick", primary: ["core", "hip_flexors"], secondary: [], equipment: "bodyweight", pattern: "core" },
  { name: "Hollow body hold", primary: ["core"], secondary: ["hip_flexors"], equipment: "bodyweight", pattern: "core" },
  { name: "Superman hold", primary: ["back", "glutes"], secondary: ["shoulders", "core"], equipment: "bodyweight", pattern: "core" },
  { name: "Shoulder tap", primary: ["core", "shoulders"], secondary: ["chest"], equipment: "bodyweight", pattern: "core" },
  { name: "Plank jack", primary: ["core"], secondary: ["shoulders", "glutes"], equipment: "bodyweight", pattern: "core" },
  { name: "Bird dog", primary: ["core"], secondary: ["glutes"], equipment: "bodyweight", pattern: "core" },
  {
    name: "Butterfly sit-up",
    aliases: ["Butterfly situps", "Butterfly sit-up", "Butterfly sit up"],
    primary: ["core"],
    secondary: ["hip_flexors"],
    equipment: "bodyweight",
    pattern: "core",
  },
  {
    name: "DB overhead march",
    aliases: ["DB overhead marches", "Dumbbell overhead march", "Dumbbell overhead marches"],
    primary: ["core", "shoulders"],
    secondary: ["hip_flexors", "glutes"],
    equipment: "dumbbell",
    pattern: "carry",
  },

  // === PLYO & CONDITIONING ===
  { name: "Broad jump", primary: ["quads", "glutes"], secondary: ["calves", "hamstrings"], equipment: "bodyweight", pattern: "plyo" },
  { name: "Box jump", primary: ["quads", "glutes"], secondary: ["calves"], equipment: "bodyweight", pattern: "plyo" },
  { name: "Forward lunge", primary: ["quads", "glutes"], secondary: ["hamstrings", "core"], equipment: "bodyweight", pattern: "squat" },
  { name: "Lateral lunge", primary: ["glutes", "quads"], secondary: ["hamstrings", "core"], equipment: "bodyweight", pattern: "squat" },
  { name: "Reverse lunge", primary: ["quads", "glutes"], secondary: ["hamstrings", "core"], equipment: "bodyweight", pattern: "squat" },
  { name: "Burpee", primary: ["chest", "quads"], secondary: ["shoulders", "core"], equipment: "bodyweight", pattern: "plyo" },
  { name: "Split squat jump", primary: ["quads", "glutes"], secondary: ["hamstrings", "calves"], equipment: "bodyweight", pattern: "plyo" },
  { name: "Tuck jump", primary: ["quads", "core"], secondary: ["glutes", "calves"], equipment: "bodyweight", pattern: "plyo" },
  { name: "Half burpee w/ dumbbell", primary: ["chest", "quads"], secondary: ["shoulders", "core"], equipment: "dumbbell", pattern: "plyo" },
  { name: "DB snatch", primary: ["shoulders", "glutes"], secondary: ["back", "core"], equipment: "dumbbell", pattern: "plyo" },
  { name: "Wall ball shot", primary: ["quads", "shoulders"], secondary: ["glutes", "core"], equipment: "other", pattern: "conditioning" },
  { name: "Medicine ball slam", primary: ["core", "shoulders"], secondary: ["back", "glutes"], equipment: "other", pattern: "conditioning" },
  { name: "Tall-kneeling rotational medicine ball slam", primary: ["core", "shoulders"], secondary: ["back", "glutes"], equipment: "other", pattern: "conditioning" },
  {
    name: "DB side lunge to high pull",
    primary: ["glutes", "quads", "shoulders"],
    secondary: ["back", "core", "hamstrings"],
    equipment: "dumbbell",
    pattern: "conditioning",
  },
  {
    name: "Woman maker",
    aliases: ["Woman makers"],
    primary: ["shoulders", "chest", "core"],
    secondary: ["back", "triceps", "quads", "glutes"],
    equipment: "dumbbell",
    pattern: "conditioning",
  },
  { name: "Ski erg", primary: ["back", "shoulders"], secondary: ["core", "triceps"], equipment: "other", pattern: "conditioning" },
  { name: "Rowing machine", primary: ["back", "quads"], secondary: ["hamstrings", "biceps", "core"], equipment: "other", pattern: "conditioning" },
  { name: "Assault bike", primary: ["quads"], secondary: ["shoulders", "core"], equipment: "other", pattern: "conditioning" },
  { name: "Battle ropes", primary: ["shoulders", "core"], secondary: ["back"], equipment: "other", pattern: "conditioning" },
  { name: "Jump rope", primary: ["calves"], secondary: ["quads", "core"], equipment: "other", pattern: "conditioning" },
  { name: "Sled push", primary: ["quads", "glutes"], secondary: ["core", "calves"], equipment: "other", pattern: "conditioning" },
  { name: "Farmer carry", primary: ["core"], secondary: ["shoulders", "back"], equipment: "dumbbell", pattern: "carry" },
  { name: "Suitcase carry", primary: ["core"], secondary: ["shoulders"], equipment: "dumbbell", pattern: "carry" },

  // === HIP ADDUCTORS ===
  { name: "Adductor machine", primary: ["adductors"], secondary: [], equipment: "machine", pattern: "squat" },
  { name: "Copenhagen plank", primary: ["adductors", "core"], secondary: ["glutes"], equipment: "bodyweight", pattern: "core" },
  { name: "Cable hip adduction", primary: ["adductors"], secondary: ["glutes"], equipment: "cable", pattern: "squat" },

  // === CALVES ===
  { name: "Standing calf raise", primary: ["calves"], secondary: [], equipment: "machine", pattern: "squat" },
  { name: "Seated calf raise", primary: ["calves"], secondary: [], equipment: "machine", pattern: "squat" },
  { name: "Single-leg calf raise", primary: ["calves"], secondary: [], equipment: "bodyweight", pattern: "squat" },
];

const exerciseSearchKey = (value: string): string => normalizeSearch(value);

const EXERCISE_INDEX: Map<string, Exercise> = new Map(
  EXERCISES.flatMap((ex) =>
    [ex.name, ...(ex.aliases ?? [])].map((name) => [exerciseSearchKey(name), ex] as const),
  )
);

export const findExercise = (name: string): Exercise | undefined =>
  EXERCISE_INDEX.get(exerciseSearchKey(name));

export const canonicalExerciseName = (name: string): string =>
  findExercise(name)?.name ?? name.trim();
