export type FinisherTemplate = {
  id: string;
  label: string;
  exercises: string[];
  rounds: number;
  repScheme: string;
  tags: ("upper" | "lower" | "core" | "conditioning")[];
  requiresHardMode?: boolean;
};

export const FINISHER_TEMPLATES: FinisherTemplate[] = [
  {
    id: "mechanical_pushup_drop",
    label: "mechanical advantage drop set",
    exercises: ["Archer push-up", "Push-up", "Incline push-up"],
    rounds: 3,
    repScheme: "5 reps each, no rest · drop set",
    tags: ["upper", "conditioning"],
    requiresHardMode: true,
  },
  {
    id: "lunge_trip",
    label: "bi-directional lunge complex",
    exercises: ["Forward lunge", "Lateral lunge", "Reverse lunge"],
    rounds: 3,
    repScheme: "6 reps/side each direction · stay on one side before switching",
    tags: ["lower", "conditioning"],
  },
  {
    id: "burpee_ladder",
    label: "burpee ladder",
    exercises: ["Burpee", "Bodyweight squat"],
    rounds: 2,
    repScheme: "Burpees 1→5→1, air squats 10 each rung",
    tags: ["conditioning", "lower"],
    requiresHardMode: true,
  },
  {
    id: "hollow_superman",
    label: "hollow-to-superman roll",
    exercises: ["Hollow body hold", "Superman hold"],
    rounds: 4,
    repScheme: "8 reps each + controlled roll transition",
    tags: ["core", "conditioning"],
  },
  {
    id: "plank_traveler",
    label: "plank traveler",
    exercises: ["Plank", "Plank to push-up", "Plank jack", "Shoulder tap"],
    rounds: 3,
    repScheme: "10 reps each, non-stop travel through all positions",
    tags: ["upper", "core", "conditioning"],
  },
  {
    id: "bear_box",
    label: "bear crawl box",
    exercises: ["Bear crawl", "Bear plank shoulder tap", "High knees"],
    rounds: 3,
    repScheme: "20 crawl steps + 8 taps + 20 high knees",
    tags: ["lower", "core", "conditioning"],
  },
  {
    id: "wall_ball_sprint",
    label: "wall-ball sprint",
    exercises: ["Wall ball shot", "High knees"],
    rounds: 3,
    repScheme: "15 wall ball shots + 20 high knees + 15 wall ball shots",
    tags: ["lower", "upper", "conditioning"],
  },
  {
    id: "slam_and_sprawl",
    label: "slam-and-sprawl chain",
    exercises: ["Tall-kneeling rotational medicine ball slam", "Burpee", "Bear crawl"],
    rounds: 3,
    repScheme: "10 slams + 8 burpees + 20 crawl steps",
    tags: ["upper", "core", "conditioning"],
    requiresHardMode: true,
  },
  {
    id: "wall_sit_burnout",
    label: "wall-sit burnout",
    exercises: ["Banded wall sit abduction pulses", "Lateral lunge"],
    rounds: 3,
    repScheme: "12 pulses + 8/side lunges + 12 pulses",
    tags: ["lower", "conditioning"],
  },
  {
    id: "dumbbell_burner",
    label: "dumbbell burner",
    exercises: ["Half burpee w/ dumbbell", "Push-up to renegade row", "DB snatch"],
    rounds: 3,
    repScheme: "8 reps each, no rest · metabolic chain",
    tags: ["upper", "lower", "conditioning"],
    requiresHardMode: true,
  },
  {
    id: "skater_shuffle",
    label: "skater shuffle",
    exercises: ["Skater hop", "Mountain climber", "High knees"],
    rounds: 3,
    repScheme: "10/side hops + 16 climbers + 20 high knees, no rest between",
    tags: ["lower", "core", "conditioning"],
  },
  {
    id: "broad_jump_chain",
    label: "broad jump chain",
    exercises: ["Broad jump", "Bodyweight squat", "Mountain climber"],
    rounds: 3,
    repScheme: "5 broad jumps + 12 squats + 16 climbers",
    tags: ["lower", "conditioning"],
  },
  {
    id: "carry_and_crawl",
    label: "carry-and-crawl gauntlet",
    exercises: ["Farmer carry", "Bear crawl", "Tuck-up"],
    rounds: 3,
    repScheme: "30-step carry + 20 crawl steps + 12 tuck-ups",
    tags: ["core", "conditioning"],
  },
  {
    id: "tuck_and_tap",
    label: "tuck-jump and tap chain",
    exercises: ["Tuck jump", "Push-up", "Hanging knee raise"],
    rounds: 3,
    repScheme: "8 tuck jumps + 10 push-ups + 12 knee raises",
    tags: ["upper", "lower", "core", "conditioning"],
  },
  {
    id: "core_conditioning_chain",
    label: "core conditioning chain",
    exercises: ["V-up", "Side plank", "Squat thrust"],
    rounds: 3,
    repScheme: "12 V-ups + 20 sec/side plank + 10 squat thrusts",
    tags: ["core", "conditioning"],
  },
  {
    id: "rotation_and_pop_chain",
    label: "rotation and pop chain",
    exercises: ["Alternating V-up", "Bird dog", "Squat jump"],
    rounds: 3,
    repScheme: "10/side V-ups + 8/side bird dogs + 10 squat jumps",
    tags: ["core", "conditioning"],
  },
  {
    id: "unilateral_carry_circuit",
    label: "unilateral carry circuit",
    exercises: ["Single-side V-up", "Copenhagen plank", "Suitcase carry"],
    rounds: 3,
    repScheme: "8/side V-ups + 20 sec/side plank + 30-step carry",
    tags: ["core", "conditioning"],
  },
  {
    id: "anti_extension_march",
    label: "anti-extension march",
    exercises: ["Dead bug", "High plank", "DB overhead march"],
    rounds: 3,
    repScheme: "10/side dead bugs + 20 sec plank hold + 20-step march",
    tags: ["core", "conditioning"],
  },
  {
    id: "hanging_core_complex",
    label: "hanging core complex",
    exercises: ["Hanging leg raise", "Cable woodchop", "DB renegade row"],
    rounds: 3,
    repScheme: "10 leg raises + 10/side woodchops + 8/side rows",
    tags: ["core", "conditioning"],
  },
  {
    id: "bicycle_and_clean_chain",
    label: "bicycle and clean chain",
    exercises: ["Bicycle crunch", "Side plank dip", "DB squat to clean"],
    rounds: 3,
    repScheme: "16 bicycle crunches + 8/side plank dips + 8 squat-to-cleans",
    tags: ["core", "conditioning"],
  },
  {
    id: "flutter_and_drag_burner",
    label: "flutter and drag burner",
    exercises: ["Flutter kick", "Plank drag", "Woman maker"],
    rounds: 3,
    repScheme: "20 flutter kicks + 8/side plank drags + 6 woman makers",
    tags: ["core", "conditioning"],
  },
  {
    id: "twist_and_pull_chain",
    label: "twist and pull chain",
    exercises: ["Butterfly sit-up", "DB side plank rotation", "DB side lunge to high pull"],
    rounds: 3,
    repScheme: "12 sit-ups + 8/side rotations + 8/side lunge-to-pulls",
    tags: ["upper", "core", "conditioning"],
  },
  {
    id: "rotational_core_gauntlet",
    label: "rotational core gauntlet",
    exercises: ["Oblique twist", "Russian twist", "Pallof press", "Ab wheel rollout"],
    rounds: 3,
    repScheme: "16 reps each, controlled tempo throughout",
    tags: ["core"],
  },
  {
    id: "power_core_chain",
    label: "power and core chain",
    exercises: ["DB clean -> press", "Kneeling chop", "Mountain climber"],
    rounds: 3,
    repScheme: "8 clean-to-press + 10/side chops + 16 climbers",
    tags: ["upper", "core", "conditioning"],
  },
  {
    id: "nordic_glute_finisher",
    label: "Nordic curl and glute bridge",
    exercises: ["Nordic hamstring curl", "Glute bridge"],
    rounds: 3,
    repScheme: "6 Nordic curls (eccentric focus) + 15 glute bridges",
    tags: ["lower", "conditioning"],
  },
  {
    id: "kb_swing_glute_bridge",
    label: "KB swing and glute bridge",
    exercises: ["Kettlebell swing", "Glute bridge"],
    rounds: 3,
    repScheme: "12 KB swings + 15 glute bridges, continuous",
    tags: ["lower", "conditioning"],
  },
];
