// Central planner tuning knobs.
// Keep this file focused on behavior weights and thresholds, not presentation
// details like rep schemes or template copy.

export const PLANNER_TUNING = {
  // Broad session-classification rules used for manual/imported workout bias.
  workoutBias: {
    strongLowerStressMultiplier: 1.1,
    directArmStimulusMultiplier: 0.35,
    lowerLeadThreshold: 3,
    upperLeadThreshold: 3.5,
    upperStrongLowerCap: 4,
  },

  // Weekly lower-vs-upper balancing when explicit plan slots are missing.
  weeklyBiasBalance: {
    strongLowerFloor: 4,
    lowerStimulusFloor: 6,
    sideLeadThreshold: 2,
    strongLowerSplitLower: 0.75,
    strongLowerSplitUpper: 0.25,
    mixedSplit: 0.5,
  },

  // Scoring for matching logged/manual workouts back onto split slots.
  slotInference: {
    targetMatchWeight: 2.4,
    focusMatchWeight: 1.25,
    offTargetPrimaryPenalty: 0.35,
    preferredMovementWeight: 1.2,
    crossBiasMovementWeight: 0.15,
    allowedMovementWeight: 0.6,
    carryCoreFocusWeight: 0.75,
    upperStrongLowerPenalty: 3,
    lowerBackShoulderPenalty: 0.35,
    lowerDirectArmPenalty: 0.5,
    focusPrimaryWeight: 0.8,
    targetPrimaryWeight: 0.35,
    focusSecondaryWeight: 0.3,
    lowerStrongAnchorBonus: 0.45,
    upperBackShoulderBonus: 0.45,
    upperDirectArmBonus: 0.3,
    lowerPosteriorPresentBonus: 0.5,
    lowerPosteriorGapPenalty: 8,
    lowerQuadImbalancePenalty: 4,
    lowerQuadPresentBonus: 0.75,
    lowerQuadGapPenalty: 8,
    lowerPosteriorImbalancePenalty: 5,
    upperStrongLowerSetThreshold: 4,
    upperStrongLowerSetPenalty: 2,
    upperMixedLowerPenalty: 10,
    armBiasNoDirectPenalty: 8,
    armBiasDirectBonus: 0.75,
    mixedExplicitSkipScoreThreshold: 12,
    sameBiasCompletedMargin: 8,
    sameBiasConfidenceThreshold: 4,
    completedMargin: 5,
    lowConfidenceThreshold: 3,
  },

  // Choosing the next split slot from weekly deficits, movement need, and balance.
  splitSelection: {
    deficitCoverageWeight: 10,
    topDeficitWeight: 1.6,
    secondDeficitWeight: 0.9,
    thirdDeficitWeight: 0.45,
    preferredNeedTopWeight: 3,
    preferredNeedSecondWeight: 1.25,
    allowedNeedWeight: 0.5,
    slotOrderPenalty: 0.1,
    saturationHighThreshold: 0.9,
    saturationMediumThreshold: 0.7,
    saturationHighPenalty: 10,
    saturationMediumPenalty: 4,
    saturationOverTargetThreshold: 1.0,
    saturationOverTargetPenalty: 20,
    saturationOverTargetPenaltyScale: 20,
    saturationOverTargetMajorMuscleThreshold: 4,
    fullOverlapPenalty: 6,
    partialOverlapPenalty: 3,
    leadThreshold: 1.25,
    leadCatchupBoost: 3,
    leadSameSidePenalty: 2.5,
    leadCap: 8,
    crossWeekRecencyDays: 6,
    recentFatigueSlotPenaltyWeight: 0.9,
    lowerBiasFatigueThreshold: 6,
    lowerBiasFatiguePenaltyWeight: 1.6,
    upperPullPivotGapThreshold: 2,
    upperPullPivotBonus: 10,
    lowerBackSupportMisreadPenalty: 8,
    adaptiveUpperPullLowerFatigueThreshold: 6,
    adaptiveUpperPullPushFatigueThreshold: 4,
    adaptiveUpperPullDeficitGap: 2,
  },

  // How much the latest sessions matter when scoring overlap.
  recentSessionOverlap: {
    latestDecay: 1,
    priorDecay: 0.65,
  },

  // Per-exercise candidate scoring during workout assembly.
  exerciseSelection: {
    movementNeedWeight: 2.75,
    fallbackMovementPriorityWeight: 0.15,
    primaryFocusMultiplier: 1.2,
    secondaryFocusMultiplier: 1.1,
    userFocusPrimaryMultiplier: 1.6,
    userFocusSecondaryMultiplier: 1.3,
    secondaryClosureWeight: 0.55,
    primaryRecoveryPenaltyWeight: 0.32,
    secondaryRecoveryPenaltyWeight: 0.1,
    latestSessionPrimaryOverlapWeight: 0.16,
    latestSessionSecondaryOverlapWeight: 0.05,
    plannedPrimaryOverlapWeight: 0.12,
    plannedSecondaryOverlapWeight: 0.04,
    primaryPriorityWeight: 0.35,
    secondaryPriorityWeight: 0.2,
    deficitClosureWeight: 8.5,
    deficitMagnitudeCap: 18,
    deficitMagnitudeWeight: 0.10,
    recoveryPenaltyCap: 7.5,
    overlapPenaltyCap: 4.5,
    armBiasBudgetPenaltyMultiplier: 0.3,
    defaultBudgetPenaltyMultiplier: 0.9,
    physiquePushChestPenalty: 0.8,
    physiquePushTricepsPenalty: 0.6,
    physiqueHingeGluteBonus: 0.8,
    physiqueSingleLegGluteBonus: 0.8,
    physiqueDirectGluteBonus: 0.7,
    physiquePullBackBonus: 0.7,
    physiqueShoulderBonus: 0.5,
    physiqueArmBiasBonus: 1.2,
    strengthHeavyEquipmentBonus: 1.4,
    fullGymBarbellBonus: 0.8,
    fullGymMachineCableBonus: 0.5,
    dumbbellEnvDumbbellBonus: 0.8,
    dumbbellEnvKettlebellBonus: 0.4,
    dumbbellEnvCablePullBonus: 1.8,
    dumbbellEnvBackFocusedCablePullBonus: 2.2,
    dumbbellEnvCableVerticalPullBonus: 1.1,
    homeConditioningBonus: 1.1,
    homeDumbbellBonus: 0.3,
    homeDumbbellHingePenalty: 0.4,
    beginnerTechnicalBarbellPenalty: 1.2,
    beginnerNovelLiftPenalty: 0.8,
    barbellCapPenalty: 12,
    stalledExercisePenalty: 7,
    watchedExercisePenalty: 2.5,
    stalledFamilySubBonus: 1.6,
    knownExerciseBonus: 1,
    earlyBackAnchorBonus: 2.4,
    earlyBackSupportPenalty: 1.8,
    upperPullRepeatVerticalPenalty: 12,
    upperPullNeedsRowPenalty: 4,
    upperPullRowBalanceBonus: 3,
    upperPullSupportBeforeRowPenalty: 3,
    preferredMovementBonus: 0.9,
    repeatExercisePenalty: 2.4,
    repeatExerciseStrengthPenalty: 0.6,
    repeatFamilyPenalty: 1.2,
    repeatFamilyStrengthPenalty: 0.4,
    repeatClaimedFamilyPenalty: 4,
    repeatClaimedFamilyStrengthPenalty: 1.5,
    repeatDirectArmIsolationPenalty: 10,
    unilateralFamilyPenalty: 7,
    repeatedUnilateralFamilyPenalty: 12,
    repeatedSingleLegPenalty: 2.5,
    repeatedSingleLegHardPenalty: 8,
    repeatedHingePenalty: 3,
    repeatedHingeHardPenalty: 8,
    repeatedDeadliftFamilyPenalty: 20,
    posteriorChainOverloadPenalty: 100,
    lowerBiasUpperMovementBudgetPenaltyMultiplier: 0.3,
    repeatedRdlFamilyPenalty: 6,
    recentLowerFamilyRepeatPenalty: 2.5,
    focusPrimaryBonus: 0.6,
    targetRemainingWeight: 0.1,
    targetReachedPenalty: 0.35,
    focusSecondaryBonus: 0.15,
    randomnessWeight: 2.0,
  },

  // How wide the random draw over candidate finisher templates is — a larger
  // spread pulls more templates into the weighted draw instead of collapsing
  // to whichever 1-3 templates score closest to the top.
  finisherVariety: {
    templateShortlistSpread: 2.5,
  },

  // Total per-session recovery budget and how finishers count against it.
  fatigueBudget: {
    baseThreeDay: 30,
    baseFourDay: 25,
    baseFiveDay: 21,
    hardModeBonus: 4,
    lowerBiasBonus: 2,
    strengthBonus: 2,
    homePenalty: 1,
    finisherStressMultiplier: 0.6,
    finisherBudgetPenaltyMultiplier: 0.75,
  },

  // Thresholds for user-facing rationale messaging.
  rationale: {
    recentFocusStressThreshold: 0.75,
    recentFocusDisplayLimit: 3,
    budgetHighThreshold: 0.9,
    budgetMediumThreshold: 0.75,
  },
} as const;
